source 'http://rubygems.org'
ruby "2.4.0"

gem 'sinatra'
gem 'activerecord', :require => 'active_record'
gem 'sinatra-activerecord', :require => 'sinatra/activerecord'
gem 'i18n'
gem 'bcrypt'
gem 'pg'
gem 'pony'
gem 'pry'
gem 'rack-flash3'
gem 'rake'
gem 'require_all'
gem 'shotgun'
gem 'thin'
